# SPDX-License-Identifier: Apache-2.0
"""D4 regression test: the brief found Core/Inc/ekf.h hand-copied out of
sync with config.py (TAU 0.1f vs 0.3, EKF_Q_VAR 2.0f vs 0.5). paci_params.h
is generated by tools/gen_params.py and must never be hand-edited; this test
(and the equivalent CI step) regenerates it to a scratch path and diffs
against the committed copy.
"""
import filecmp
import os
import sys
import tempfile

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_COMMITTED = os.path.join(_PROJECT_ROOT, "paci_core", "include", "paci_params.h")


def test_paci_params_h_matches_config_py():
    with tempfile.TemporaryDirectory() as tmp:
        script = os.path.join(_PROJECT_ROOT, "tools", "gen_params.py")
        env = dict(os.environ)
        # Point the generator at a scratch output path without touching the
        # real gen_params.py CLI (it always writes to the real repo path);
        # instead re-run its rendering function directly against a temp file.
        sys.path.insert(0, _PROJECT_ROOT)
        import tools.gen_params as gen_params  # noqa: E402

        scratch = os.path.join(tmp, "paci_params.h")
        header = gen_params.render_header()
        with open(scratch, "w", newline="\n", encoding="ascii") as f:
            f.write(header)

        assert os.path.isfile(_COMMITTED), (
            "paci_core/include/paci_params.h is missing — run "
            "`python tools/gen_params.py` and commit the result."
        )
        assert filecmp.cmp(scratch, _COMMITTED, shallow=False), (
            "paci_core/include/paci_params.h is out of date relative to "
            "config.py. Run `python tools/gen_params.py` and commit the "
            "regenerated header."
        )
