// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen_params.py from config.py -- DO NOT EDIT BY HAND.
// Regenerate with: python tools/gen_params.py
#ifndef PACI_PARAMS_H
#define PACI_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

#define PACI_TAU 0.3f
#define PACI_Q_VAR 0.5f
#define PACI_R_VAR 4.0f
#define PACI_P0_VAR 10.0f
#define PACI_CHI2_THRESHOLD_95 3.841f
#define PACI_PHYSICS_ALPHA 0.6f
#define PACI_PHYSICS_BETA 0.4f
#define PACI_PHYSICS_GAMMA 0.3f
#define PACI_PHYSICS_EA 0.15f
#define PACI_KB_EV 8.617e-05f
#define PACI_P_REF 50.0f
#define PACI_T_REF 323.15f
#define PACI_W_REF 500.0f
#define PACI_F_REF 100.0f
#define PACI_ETCH_RATE_NOMINAL 250.0f
#define PACI_NORM_SCALE 50.0f

#define PACI_WATCHDOG_INTERVAL 50
#define PACI_BURN_IN_STEPS 30

#ifdef __cplusplus
}
#endif

#endif // PACI_PARAMS_H
