// SPDX-License-Identifier: Apache-2.0
// Generated by tools/export_cmsisnn.py -- DO NOT EDIT BY HAND.
#ifndef PACI_TIER1_WEIGHTS_H
#define PACI_TIER1_WEIGHTS_H

#include <stdint.h>

#define PACI_EXPORT_SHA "f5082f36667fcde6"

// tier1_conv1 (CONV_2D), weight shape [8, 1, 5, 1]
static const int8_t tier1_conv1_weight[40] = {-22, -5, -29, 127, -62, -86, -53, 7, 127, 2, 21, 119, -16, -127, 1, 36, 59, -53, -127, 82, -127, -74, 55, 40, 76, -107, -72, 127, 27, 35, -127, 56, 70, -7, 66, -29, 2, -127, 39, 104};
static const int32_t tier1_conv1_bias[8] = {123, -9, -24, -646, -711, 1655, -4473, -429};
static const int32_t tier1_conv1_multiplier[8] = {1461673870, 1301162368, 1224166223, 1632196284, 1331341190, 1454783864, 1656333411, 1427304221};
static const int32_t tier1_conv1_shift[8] = {-6, -6, -6, -6, -7, -7, -8, -6};
#define TIER1_CONV1_INPUT_OFFSET 93
#define TIER1_CONV1_OUTPUT_OFFSET -128
#define TIER1_CONV1_N_CHANNELS 8

// tier1_conv2 (CONV_2D, INT4 packed two-per-byte), weight shape [8, 1, 3, 8], per-channel clamps=[0, 0, 0, 0, 0, 0, 0, 0] (total=0)
static const int8_t tier1_conv2_weight[96] = {126, 16, 13, 42, 30, 14, 15, -52, 2, 95, 0, -75, 78, 18, 66, 121, 33, 29, 33, 44, 46, 82, 15, -82, 94, -90, -14, 45, 61, 0, 33, -86, -46, -31, 13, -98, 17, 47, 75, -48, 27, -15, 16, 60, 33, -107, -31, 32, 2, 47, 109, -50, 11, -15, -14, 12, 112, -108, -64, 81, 16, -44, -31, -76, 112, -108, -52, 29, 31, -47, 51, 28, 1, 3, 13, -31, -1, -32, -16, 1, 18, -12, -31, 112, 63, 17, -3, 115, -51, 31, -16, 16, 65, 33, 65, 31};
static const int32_t tier1_conv2_bias[8] = {0, -61, 4, -38, -25, 4, 27, -21};
static const int32_t tier1_conv2_multiplier[8] = {1604792977, 1619042900, 2052339423, 2104487457, 1525160886, 1799014685, 1178770368, 2097336622};
static const int32_t tier1_conv2_shift[8] = {-1, -2, -2, -1, -1, -1, -1, -2};
#define TIER1_CONV2_INPUT_OFFSET 128
#define TIER1_CONV2_OUTPUT_OFFSET -128
#define TIER1_CONV2_N_CHANNELS 8

// tier1_gap (MEAN / GlobalAveragePooling1D)
#define TIER1_GAP_INPUT_OFFSET 128
#define TIER1_GAP_OUTPUT_OFFSET -128
#define TIER1_GAP_MULTIPLIER 1935798148
#define TIER1_GAP_SHIFT -2

// tier1_logits (FULLY_CONNECTED, INT4 packed two-per-byte, PER-TENSOR quant -- arm_fully_connected_s4 has no per-channel variant), weight shape [2, 8], clamps=0
static const int8_t tier1_logits_weight[8] = {68, -92, -87, 4, -51, 125, 71, -35};
static const int32_t tier1_logits_bias[2] = {-12, 12};
#define TIER1_LOGITS_MULTIPLIER 1498722186
#define TIER1_LOGITS_SHIFT -3
#define TIER1_LOGITS_INPUT_OFFSET 128
#define TIER1_LOGITS_OUTPUT_OFFSET -5

#endif // PACI_TIER1_WEIGHTS_H
