// SPDX-License-Identifier: Apache-2.0
// Generated by tools/export_cmsisnn.py -- DO NOT EDIT BY HAND.
#ifndef PACI_TIER1_WEIGHTS_H
#define PACI_TIER1_WEIGHTS_H

#include <stdint.h>

#define PACI_EXPORT_SHA "f5082f36667fcde6"

// tier1_conv1 (CONV_2D), weight shape [8, 1, 5, 1]
static const int8_t tier1_conv1_weight[40] = {45, 26, 6, 127, 43, 127, 48, -63, -64, -51, -47, 47, 18, -127, 71, -67, 84, 127, 70, 30, 104, 5, -56, 66, -127, -73, -127, 93, 15, 96, -26, 109, 127, -86, -55, -75, 37, -10, 3, 127};
static const int32_t tier1_conv1_bias[8] = {-2594, -91, -313, 1910, 556, -193, -1618, -376};
static const int32_t tier1_conv1_multiplier[8] = {1798035308, 1213454998, 1185578175, 2010246286, 1324203764, 1326644838, 1435782278, 1381856043};
static const int32_t tier1_conv1_shift[8] = {-9, -6, -6, -10, -6, -6, -7, -7};
#define TIER1_CONV1_INPUT_OFFSET 83
#define TIER1_CONV1_OUTPUT_OFFSET -128
#define TIER1_CONV1_N_CHANNELS 8

// tier1_conv2 (CONV_2D, INT4 packed two-per-byte), weight shape [8, 1, 3, 8], per-channel clamps=[0, 0, 0, 0, 0, 0, 0, 0] (total=0)
static const int8_t tier1_conv2_weight[96] = {97, -30, -12, 19, 60, 76, 2, 42, 112, -37, -63, 95, 95, 30, 124, -42, 35, 17, 28, 31, 29, 4, -4, -33, -14, 49, 33, -55, 18, 28, 34, 30, 0, -46, 67, 60, 126, 77, -45, 51, -18, -68, -94, 47, 78, 1, 84, -2, 16, -50, 58, -64, 126, 32, 1, -48, -28, 31, 94, -47, -60, -2, -78, -45, -34, 61, -5, -57, -30, -1, -101, -62, 126, -17, -111, 53, 45, -69, -47, -2, 31, 78, 37, 19, 14, 48, 1, -21, -1, 25, -12, -21, 124, 51, -99, -79};
static const int32_t tier1_conv2_bias[8] = {-28, 60, -64, -54, 77, 114, -45, 66};
static const int32_t tier1_conv2_multiplier[8] = {1580571411, 1482111427, 1931451080, 1103091082, 1304696904, 1644482287, 2073387586, 1413289388};
static const int32_t tier1_conv2_shift[8] = {-4, -2, -2, -3, -3, -4, -4, -4};
#define TIER1_CONV2_INPUT_OFFSET 128
#define TIER1_CONV2_OUTPUT_OFFSET -128
#define TIER1_CONV2_N_CHANNELS 8

// tier1_gap (MEAN / GlobalAveragePooling1D)
#define TIER1_GAP_INPUT_OFFSET 128
#define TIER1_GAP_OUTPUT_OFFSET -128
#define TIER1_GAP_MULTIPLIER 1269313929
#define TIER1_GAP_SHIFT -1

// tier1_logits (FULLY_CONNECTED, INT4 packed two-per-byte, PER-TENSOR quant -- arm_fully_connected_s4 has no per-channel variant), weight shape [2, 8], clamps=0
static const int8_t tier1_logits_weight[8] = {34, 105, -45, -15, -52, -27, 45, 59};
static const int32_t tier1_logits_bias[2] = {95, -95};
#define TIER1_LOGITS_MULTIPLIER 1261453817
#define TIER1_LOGITS_SHIFT -3
#define TIER1_LOGITS_INPUT_OFFSET 128
#define TIER1_LOGITS_OUTPUT_OFFSET 28

#endif // PACI_TIER1_WEIGHTS_H
