# SPDX-License-Identifier: Apache-2.0
"""Generate paci_core/include/paci_params.h from config.py.

config.py is the single source of truth for every physics/EKF/scheduler
constant (D4: the brief found the C filter's TAU/Q_VAR hand-copied out of
sync with config.py). This script is the only thing allowed to write
paci_params.h; CI regenerates it and runs `git diff --exit-code` to catch
drift (see .github/workflows/arm-bench.yml, Phase 6).

Usage: python tools/gen_params.py
"""
import os
import sys

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _PROJECT_ROOT)

import config  # noqa: E402

_OUTPUT_PATH = os.path.join(_PROJECT_ROOT, "paci_core", "include", "paci_params.h")

# (C macro name, config.py attribute, C type)
_FLOAT_PARAMS = [
    ("PACI_TAU", "TAU"),
    ("PACI_Q_VAR", "Q_VAR"),
    ("PACI_R_VAR", "R_VAR"),
    ("PACI_P0_VAR", "P0_VAR"),
    ("PACI_CHI2_THRESHOLD_95", "CHI2_THRESHOLD_95"),
    ("PACI_PHYSICS_ALPHA", "PHYSICS_ALPHA"),
    ("PACI_PHYSICS_BETA", "PHYSICS_BETA"),
    ("PACI_PHYSICS_GAMMA", "PHYSICS_GAMMA"),
    ("PACI_PHYSICS_EA", "PHYSICS_EA"),
    ("PACI_KB_EV", "KB_EV"),
    ("PACI_P_REF", "P_REF"),
    ("PACI_T_REF", "T_REF"),
    ("PACI_W_REF", "W_REF"),
    ("PACI_F_REF", "F_REF"),
    ("PACI_ETCH_RATE_NOMINAL", "ETCH_RATE_NOMINAL"),
    ("PACI_NORM_SCALE", "NORM_SCALE"),
]

_INT_PARAMS = [
    ("PACI_WATCHDOG_INTERVAL", "WATCHDOG_INTERVAL"),
    ("PACI_BURN_IN_STEPS", "BURN_IN_STEPS"),
]

# config.py also defines PHYSICS_K0, DT and ADAPTIVE_WINDOW. PHYSICS_K0 is
# never read by phase1_physics.physics_model.PhysicsModel.etch_rate (the
# nominal-rate multiplier used there is ETCH_RATE_NOMINAL, not k0), DT is
# unused because the state-transition relaxation already folds the timestep
# into TAU, and ADAPTIVE_WINDOW only feeds phase3_scheduler's unused rolling
# stats (see its docstring: "we do NOT adapt the threshold itself"). None of
# the three affect paci_core's decision logic, so they are intentionally not
# emitted — generating unused macros would be dead code on the C side.


def _format_float(value):
    return f"{float(value)!r}f"


def render_header():
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by tools/gen_params.py from config.py -- DO NOT EDIT BY HAND.",
        "// Regenerate with: python tools/gen_params.py",
        "#ifndef PACI_PARAMS_H",
        "#define PACI_PARAMS_H",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for macro, attr in _FLOAT_PARAMS:
        lines.append(f"#define {macro} {_format_float(getattr(config, attr))}")
    lines.append("")
    for macro, attr in _INT_PARAMS:
        lines.append(f"#define {macro} {int(getattr(config, attr))}")
    lines += [
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif // PACI_PARAMS_H",
        "",
    ]
    return "\n".join(lines)


def main():
    header = render_header()
    os.makedirs(os.path.dirname(_OUTPUT_PATH), exist_ok=True)
    with open(_OUTPUT_PATH, "w", newline="\n", encoding="ascii") as f:
        f.write(header)
    print(f"Wrote {_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
